---
title: "todonotes"
author: "Ingo Rohlfing, Ayjeren Rozyjumayeva"
date: "25 5 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### To do




**conds_upset**
- documentation says input should be dataframe, but it also works with a list
- IR: I changed documentation and example to list; df and list now options
- for AR: In example, AB is not decomposed into A and B, as it should be

**cons_minimum**
- We need an example of existing solutions that are imported


# Addressed

**Counting**  
- for AR: Done
- By AR: But needs to be checked imported datasets as the new function was introduced.

**Comparison**  
- by IR: Should be good

**config_upset**
- what does const and y option do? Is it a consistency threshold? Is this needed when we have cons_minimum function?

Correct. No noeed for the y anymore. 

**detection**

- original documentation said: "Needs further reworking to get rid of the for loop at later stages" <= is this necessary?

- JR: No, not necessary. In fact, I could not find a more efficient solution to using the loop. 
 
**cov_minimum**
- formerly dt.selector 2. Renamed it to have a meaningful function name
complemeting cons_minimum
